# Generated by Django 2.2.7 on 2019-11-14 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('image_uri', models.URLField(max_length=400)),
                ('jersey_number', models.IntegerField(default=0)),
                ('Country', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo_uri', models.URLField(max_length=400)),
                ('club_state', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(verbose_name='date added')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_count', models.IntegerField(default=0)),
                ('runs_count', models.IntegerField(default=0)),
                ('highest_score', models.IntegerField(default=0)),
                ('fifties_count', models.IntegerField(default=0)),
                ('hundreds_count', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Team'),
        ),
    ]
